149 implement document query service
Onto-Med/top-backend pull request #171
Opened 2023-09-28 15:04 UTC by fmatthies

2023-09-28 15:06 UTC, fmatthies commented
depending on top-api (I made a version increase there 0.9.1 -> 0.9.2) the version needs to be adjusted here as well; this is the conflict

2023-09-29 07:05 UTC, ChristophB requested changes

2023-09-29 07:05 UTC, ChristophB commented on src/main/java/care/smith/top/backend/service/nlp/DocumentService.java
> +//    Page<DocumentEntity> documentPageEntity = documentRepository.findDocumentEntitiesByIdIn(ids, pageRequestOf(page));
In order for this to work correctly, I think the method name needs to be adjusted.

Something like: "findAllByIdIn"

The same applies to the other `DocumentRepository` methods.

2023-09-29 07:48 UTC, fmatthies commented on src/main/java/care/smith/top/backend/service/nlp/DocumentService.java
> +//    Page<DocumentEntity> documentPageEntity = documentRepository.findDocumentEntitiesByIdIn(ids, pageRequestOf(page));
Yeah, I thought so, but there is no "findAllByIdIn"; if I want something with "In" I only get this kind of method with "DocumentEntities" recommended

2023-09-29 07:52 UTC, fmatthies reviewed
all suggestions resolved as possible

2023-09-29 09:20 UTC, ChristophB approved these changes

2023-09-29 09:29 UTC, merged