Add concept cluster creation functionality
Onto-Med/top-backend pull request #188
Opened 2024-01-09 14:39 UTC by fmatthies

This pull requests adds the functionality to create concept clusters (basically graph structures that relate documents to concepts to phrases) in `Neo4j` from concept graphs that were created with the `concept-graphs-api`

2024-01-10 15:29 UTC, ChristophB requested changes

2024-01-10 15:29 UTC, ChristophB commented on src/main/java/care/smith/top/backend/model/neo4j/ConceptNodeEntity.java
>    // ToDo: this takes a long time to load; maybe it's not necessary bc I get the Phrases later with
Please finish this TODO

2024-01-10 15:29 UTC, ChristophB commented on src/main/java/care/smith/top/backend/repository/neo4j/PhraseNodeRepository.java
>            // ToDo: implement check for whether all or only exemplars should be regarded
Please finish this TODO

2024-01-10 15:29 UTC, ChristophB commented on src/main/java/care/smith/top/backend/service/nlp/ConceptClusterService.java
> +                      // ToDo: threading of single graph creation seems to be not working; throws
Please finish this TODO

2024-01-10 15:29 UTC, ChristophB commented on src/test/java/care/smith/top/backend/service/nlp/ConceptClusterServiceTest.java
> +  @Test
No test implementations

2024-01-15 08:11 UTC, fmatthies commented on src/main/java/care/smith/top/backend/model/neo4j/ConceptNodeEntity.java
>    // ToDo: this takes a long time to load; maybe it's not necessary bc I get the Phrases later with
removed this TODO without changing anything. I need this to create the relations when generating the neo4j graphs.

2024-01-15 08:24 UTC, fmatthies commented on src/main/java/care/smith/top/backend/service/nlp/ConceptClusterService.java
> +                      // ToDo: threading of single graph creation seems to be not working; throws
made an issue out of it

2024-01-15 15:02 UTC, ChristophB approved these changes

2024-01-15 15:03 UTC, merged