Support multiple document sources
Onto-Med/top-backend pull request #209
Opened 2024-05-07 10:37 UTC by fmatthies

A plethora of improvement/changes were made to properly access/do the concept graph and concept cluster creation from the backend. This relates to `Elasticsearch`, `Neo4j` as well as the `concept-graph-api`.

2024-05-08 13:56 UTC, ChristophB requested changes

2024-05-08 13:56 UTC, ChristophB commented on src/main/java/care/smith/top/backend/api/nlp/ConceptClusterApiDelegateImpl.java
> +    // ToDo: another response than void?
Resolve this TODO comment

2024-05-08 13:56 UTC, ChristophB commented on src/main/java/care/smith/top/backend/api/nlp/ConceptPipelineApiDelegateImpl.java
> +    // ToDo: another response than void?
Resolve this TODOs

2024-05-13 14:50 UTC, fmatthies commented on src/main/java/care/smith/top/backend/service/nlp/ConceptClusterService.java
> +  // ToDo: think about: right now, the filtering of concepts by their corpusId is not made in neo4j
Created a new issue (but low priority)

2024-05-14 07:53 UTC, fmatthies commented on src/main/java/care/smith/top/backend/api/nlp/ConceptClusterApiDelegateImpl.java
> +    // ToDo: another response than void?
since changes in top-api would be needed, I created a new issue for this

2024-05-14 07:53 UTC, fmatthies commented on src/main/java/care/smith/top/backend/api/nlp/ConceptPipelineApiDelegateImpl.java
> +    // ToDo: another response than void?
since changes in top-api would be needed, I created a new issue for this

2024-05-14 08:58 UTC, fmatthies commented on src/test/resources/neo4j-graphs/backend-test-graph.graphml
there might be other ways, but this is just a reference for writing tests to have the graph structure visualized (this is the source file to recreate the png if the test graph needs to be changed)

2024-05-14 08:59 UTC, fmatthies commented on src/test/resources/neo4j-graphs/backend-test-graph.png
there might be other ways, but this is just a reference for writing tests to have the graph structure visualized

2024-05-14 09:31 UTC, fmatthies commented on src/main/java/care/smith/top/backend/service/nlp/ConceptGraphsService.java
> +    // ToDo: need to implement proper checkable status in concept-graphs-api
Checked and `concept-graphs-api` was not really the culprit, but rather `top-document-query`. Created an issue, accordingly.

2024-05-16 12:29 UTC, fmatthies commented on src/main/java/care/smith/top/backend/service/nlp/ConceptClusterService.java
> +      // ToDo: !
Removed todo → this was for catching the IOException. However, I checked in `top-document-query` the `getDocumentsByIdsBatched` and this doesn't need to throw the exception (removed it there for the next bugfix release)

2024-05-16 13:41 UTC, fmatthies commented on src/test/java/care/smith/top/backend/api/nlp/ConceptClusterApiDelegateImplTest.java
> +  void createConceptClustersForPipelineId() {}
removed test; better to test functionality in appropriate service test

2024-05-16 14:13 UTC, fmatthies commented on src/test/java/care/smith/top/backend/service/nlp/ConceptGraphsServiceTest.java
> +  void getStatusOfPipeline() {}
removed test: there is no such method to test

2024-05-30 08:01 UTC, ChristophB approved these changes

2024-05-30 08:34 UTC, merged